name: C/C++ CI

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install valgrind
      run: sudo apt install -y valgrind
    - name: make
      working-directory: lab2
      run: make
    - name: make test
      working-directory: lab2
      run: make test
